platform :ios, '15.0'
install! 'cocoapods', warn_for_unused_master_specs_repo: false
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug'   => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  raise "#{generated} must exist. Run ‘flutter pub get’ first" unless File.exist?(generated)
  File.foreach(generated) { |l| return $1.strip if l =~ /FLUTTER_ROOT\=(.*)/ }
  raise 'FLUTTER_ROOT not found — delete Generated.xcconfig and run flutter pub get'
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  pod 'Firebase/Messaging'

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |t|
    flutter_additional_ios_build_settings(t)
    puts "🛠  Processing pod target: #{t.name}"

    if %w[google_sign_in_ios Pods-google_sign_in_ios].include?(t.name)
      t.build_configurations.each do |c|
        c.build_settings['GIDSignIn_SCHEME'] =
          'com.googleusercontent.apps.388298698922-frg9qq2gln7alrmf0nokvf0h0rhoroof'
      end
    end
  end
end
